name: Update Latest Release

on:
  push:
    paths:
      - 'Karing_bak.zip'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current date and time (MSK)
        id: datetime
        run: |
          echo "datetime=$(TZ='Europe/Moscow' date '+%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Delete old release tag
        run: gh release delete latest --cleanup-tag -y || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Latest Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Update backup files #${{ github.run_number }} (${{ steps.datetime.outputs.datetime }} MSK)"
          body: |
            ### 📦 Актуальный бэкап конфигурации Karing

            **Время сборки:** `${{ steps.datetime.outputs.datetime }} MSK`

            #### 🔗 Ссылка для прямого импорта:

            ```
            https://github.com/Sn1pp1/karing_backup/releases/download/latest/Karing_bak.zip
            ```

            ---
            *Архив обновляется автоматически при отправке нового `Karing_bak.zip` файла в репозиторий.*
          files: |
            Karing_bak.zip
